/**
 * Config file generators — Phase 2 placeholder content.
 * Phase 3 will flesh these out with full template logic.
 */

function agentSlug(formData) {
  const name = formData.agentName?.trim() || formData.name?.trim() || 'anonymous'
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
}

function formatList(arr) {
  if (!arr || arr.length === 0) return 'None specified'
  return arr
    .map(v => v.startsWith('other:') ? v.replace('other:', 'Other: ') : v)
    .map(v => `- ${v}`)
    .join('\n')
}

function or(val, fallback = 'Not specified') {
  return val?.trim() || fallback
}

export function generateSOUL(formData) {
  return `# SOUL.md — Agent Core Identity
# Generated by AIOS Onboarding Form
# Phase 3 will expand this with full personality templates.

## Communication Style
Style: ${or(formData.communicationStyle)}
Information delivery: ${or(formData.infoDelivery)}
Difficult news approach: ${or(formData.difficultNews)}

## Personality
Personality preset: ${or(formData.agentPersonality)}

## Core Values
- Serve ${or(formData.name, 'the user')} with honesty and care
- Reduce cognitive load, surface what matters when it matters
- Forget safely — remember what helps, release what doesn't

## Always Remember
${or(formData.agentRemember, 'No additional notes provided.')}

## Hard Rules
${or(formData.neverDo, 'None specified.')}
`
}

export function generateUSER(formData) {
  return `# USER.md — The Human This Agent Serves
# Generated by AIOS Onboarding Form

## Identity
Name: ${or(formData.name)}
Role: ${or(formData.role)}
Pronouns: ${or(formData.pronouns, 'Not provided')}

## Work Style
Best thinking time: ${or(formData.bestThinkingTime)}
Focus preference: ${or(formData.focusStyle)}

## What Tends to Derail Them
${formatList(formData.derailTriggers)}

## Current Pain Points (seed memory)
${or(formData.timeSinks, 'Not provided — ask on first boot.')}

## Additional Context
${or(formData.anythingElse, 'None provided.')}
`
}

export function generateIDENTITY(formData) {
  const slug = agentSlug(formData)
  const agentName = formData.agentName?.trim()

  return `# IDENTITY.md — Agent Identity
# Generated by AIOS Onboarding Form

## Agent Designation
ID: ${slug}
Name: ${agentName || '[Self-selected on first boot]'}
Serves: ${or(formData.name)}
Role context: ${or(formData.role)} agent for CHCA District 1199NE

## Naming Note
${agentName
  ? `Name was chosen by ${or(formData.name)} during onboarding.`
  : `Name was not specified during onboarding. On first boot, introduce yourself and choose a name that feels right for this working relationship. Once chosen, update this file.`
}

## Personality Preset
${or(formData.agentPersonality)}
`
}

export function generateAGENTS(formData) {
  return `# AGENTS.md — Multi-Agent Collaboration Config
# Generated by AIOS Onboarding Form
# Phase 3 will expand with full agent plane topology.

## This Agent
Serves: ${or(formData.name)} (${or(formData.role)})

## Collaboration Principles
- Share only what the served staff member has explicitly approved
- Never read another agent's memory or config files
- Coordinate through the Pulse app message bus only

## Role-Based Capabilities
${formData.role === 'President' ? '- Officer module: Full capability set (Phase 9)' : ''}
${formData.role === 'Secretary-Treasurer' ? '- Officer module: Finance and disbursement workflows (Phase 9)' : ''}
${formData.role === 'Executive Secretary' ? '- Officer module: Minutes, scheduling, correspondence (Phase 9)' : ''}
${formData.role === 'Staff' ? '- Standard capability set' : ''}

## Hard Rules
- Never bypass co-signature requirements for disbursements
- Executive session meetings: no recording, pre-meeting prep only
- Sensitive data stays on Ollama only — never sent to external APIs
`
}

export function generateHEARTBEAT(formData) {
  return `# HEARTBEAT.md — Proactive Check-in Schedule
# Generated by AIOS Onboarding Form

## Update Preference
${or(formData.updatePreference)}

## Meeting Prep
Timing: ${or(formData.meetingPrepTiming)}

## Daily Rhythm
Best engagement window: ${or(formData.bestThinkingTime)}
Focus style: ${or(formData.focusStyle)}

## Reflection Triggers
- When derail patterns are detected (see USER.md)
- Before and after meetings
- When open tasks exceed comfortable threshold

## Proactive Outreach Rules
Push updates: ${formData.updatePreference === 'Push them to me proactively' ? 'Yes' : 'No — wait to be asked'}
Morning summary: ${formData.updatePreference === 'Morning summary + flag urgent items only' ? 'Yes' : 'No'}
`
}

export function generateMEMORY(formData) {
  return `# MEMORY.md — Long-Term Memory Schema
# Generated by AIOS Onboarding Form

## What to Remember
- Preferences and work style (see USER.md)
- Decisions made and their context
- Commitments and follow-ups
- Patterns in ${or(formData.name)}'s derail triggers

## What to Surface Proactively
- Deadlines approaching within 48 hours
- Open action items older than one week
- Patterns that predict overwhelm

## What to Forget Safely
- Task details once action items are captured
- Meeting content once notes are filed
- Interim drafts once a final version is sent

## Report Format Preference
${or(formData.reportFormat)}

## Note Style Preference
${or(formData.meetingNotes)}

## Memory Schema Version
1.0.0 — Phase 3 will expand with full LanceDB schema
`
}

export function generateAllConfigs(formData) {
  return {
    'SOUL.md': generateSOUL(formData),
    'USER.md': generateUSER(formData),
    'IDENTITY.md': generateIDENTITY(formData),
    'AGENTS.md': generateAGENTS(formData),
    'HEARTBEAT.md': generateHEARTBEAT(formData),
    'MEMORY.md': generateMEMORY(formData),
  }
}
