"""aios planes — subcommands for managing agent planes."""

import json
import os
import subprocess
import sys
from pathlib import Path

import click
import yaml

from provisioning.cli.registry import create_plane, get_plane, list_agents, list_planes

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


@click.group()
def planes():
    """Manage agent planes."""
    pass


@planes.command()
@click.option("--name", required=True, help="Name for the new plane")
@click.option("--project", default="local", help="Project type (default: local)")
def create(name, project):
    """Create a new agent plane."""
    try:
        plane = create_plane(name)
        click.echo(f"Plane '{name}' created (project={project})")
    except ValueError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)


@planes.command()
def status():
    """Show status of all planes."""
    all_planes = list_planes()
    if not all_planes:
        click.echo("No planes registered.")
        return
    for name, plane in all_planes.items():
        agent_count = len(plane.get("agents", {}))
        click.echo(f"  {name}: {agent_count} agent(s)")
        for agent_id, agent in plane.get("agents", {}).items():
            click.echo(f"    - {agent_id} (owner={agent['owner']}, role={agent['role']})")


@planes.command()
@click.option("--plane", required=True, help="Name of the plane")
def compose(plane):
    """Generate docker-compose.yml for a plane's agents."""
    try:
        plane_data = get_plane(plane)
    except KeyError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)

    agents = plane_data.get("agents", {})
    if not agents:
        click.echo(f"Error: Plane '{plane}' has no agents. Add agents first.", err=True)
        sys.exit(1)

    plane_name = plane_data["name"]
    compose_dict = _build_compose(plane_name, agents)

    output_path = PROJECT_ROOT / "docker-compose.yml"
    with open(output_path, "w") as f:
        f.write("# AUTO-GENERATED — do not edit manually.\n")
        f.write(f"# Generated by: aios planes compose --plane {plane}\n")
        f.write("# Regenerate with the command above after adding/removing agents.\n\n")
        yaml.dump(compose_dict, f, default_flow_style=False, sort_keys=False)

    click.echo(f"Generated docker-compose.yml at {output_path}")
    click.echo(f"  Plane: {plane_name}")
    click.echo(f"  Agents: {len(agents)}")
    click.echo(f"  Network: {plane_name}-net (internal: true)")


def _build_compose(plane_name: str, agents: dict) -> dict:
    """Build a docker-compose dict for the given plane and agents."""
    services = {}
    for agent_id, agent in agents.items():
        services[f"openclaw-{agent_id}"] = {
            "image": "chca/openclaw-aios:latest",
            "container_name": f"openclaw-{agent_id}",
            "restart": "unless-stopped",
            "networks": [f"{plane_name}-net"],
            "volumes": [
                f"./agents/{agent_id}/config:/app/config:ro",
                f"./agents/{agent_id}/memory:/app/memory:rw",
            ],
            "env_file": [f"./agents/{agent_id}/.env"],
            "environment": [
                f"AGENT_ID={agent_id}",
                f"PLANE_NAME={plane_name}",
                "OLLAMA_HOST=host.docker.internal:11434",
            ],
            "extra_hosts": ["host.docker.internal:host-gateway"],
            "deploy": {
                "resources": {
                    "limits": {"cpus": "1.0", "memory": "2G"},
                    "reservations": {"memory": "512M"},
                }
            },
            "healthcheck": {
                "test": ["CMD", "curl", "-f", "http://localhost:3000/health"],
                "interval": "30s",
                "timeout": "10s",
                "retries": 3,
                "start_period": "40s",
            },
        }

    return {
        "version": "3.9",
        "networks": {
            f"{plane_name}-net": {
                "driver": "bridge",
                "internal": True,  # Security: no direct internet from agent network
                "ipam": {"config": [{"subnet": "172.20.0.0/24"}]},
            }
        },
        "services": services,
    }


@planes.command("verify-isolation")
@click.option("--plane", required=True, help="Name of the plane to verify")
def verify_isolation(plane):
    """Verify Docker isolation for all agents in a plane.

    Checks:
    - Each agent container is on its own network namespace
    - Containers cannot ping each other
    - config/ volume is mounted read-only
    - memory/ volume is writable
    """
    try:
        plane_data = get_plane(plane)
    except KeyError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)

    agents = plane_data.get("agents", {})
    if not agents:
        click.echo(f"Error: Plane '{plane}' has no agents.", err=True)
        sys.exit(1)

    plane_name = plane_data["name"]
    agent_ids = list(agents.keys())
    container_names = [f"openclaw-{aid}" for aid in agent_ids]

    click.echo(f"Verifying isolation for plane '{plane_name}' ({len(agent_ids)} agents)")
    click.echo()

    all_passed = True

    # Pre-check: identify which containers are actually running
    running_containers = set()
    click.echo("0. Container status")
    for cname in container_names:
        if _is_container_running(cname):
            running_containers.add(cname)
            click.echo(f"   ✓ {cname}: running")
        else:
            click.echo(f"   ! {cname}: not running")
            all_passed = False

    if not running_containers:
        click.echo()
        click.echo("No containers are running. Start them with 'docker compose up -d' first.")
        sys.exit(1)

    click.echo()

    # Check 1: Verify containers are on the correct network
    click.echo("1. Network namespace isolation")
    for cname in container_names:
        if cname not in running_containers:
            click.echo(f"   ! {cname}: skipped (not running)")
            continue
        passed = _check_network_namespace(cname, plane_name)
        if not passed:
            all_passed = False

    click.echo()

    # Check 2: Verify containers cannot ping each other
    click.echo("2. Cross-container connectivity (expect failure)")
    running_list = [c for c in container_names if c in running_containers]
    if len(running_list) >= 2:
        for i, src in enumerate(running_list):
            for j, dst in enumerate(running_list):
                if i >= j:
                    continue
                passed = _check_no_ping(src, dst)
                if not passed:
                    all_passed = False
    else:
        click.echo("   (skipped — need at least 2 running agents to test cross-container connectivity)")

    click.echo()

    # Check 3: config/ is read-only
    click.echo("3. Config volume read-only")
    for cname in container_names:
        if cname not in running_containers:
            click.echo(f"   ! {cname}: skipped (not running)")
            continue
        passed = _check_config_readonly(cname)
        if not passed:
            all_passed = False

    click.echo()

    # Check 4: memory/ is writable
    click.echo("4. Memory volume writable")
    for cname in container_names:
        if cname not in running_containers:
            click.echo(f"   ! {cname}: skipped (not running)")
            continue
        passed = _check_memory_writable(cname)
        if not passed:
            all_passed = False

    click.echo()
    if all_passed:
        click.echo("All isolation checks passed.")
    else:
        click.echo("Some checks failed — review warnings above.")
        sys.exit(1)


def _run_docker(args: list[str], timeout: int = 10) -> tuple[int, str, str]:
    """Run a docker command and return (returncode, stdout, stderr)."""
    try:
        result = subprocess.run(
            ["docker"] + args,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return result.returncode, result.stdout.strip(), result.stderr.strip()
    except subprocess.TimeoutExpired:
        return 1, "", "Command timed out"
    except FileNotFoundError:
        return 1, "", "docker not found — is Docker installed?"


def _is_container_running(container_name: str) -> bool:
    """Check if a Docker container is running."""
    rc, stdout, _ = _run_docker([
        "inspect", "--format", "{{.State.Running}}", container_name,
    ])
    return rc == 0 and stdout.strip().lower() == "true"


def _check_network_namespace(container_name: str, plane_name: str) -> bool:
    """Verify the container is on the expected network."""
    rc, stdout, stderr = _run_docker([
        "inspect", "--format",
        '{{range $key, $val := .NetworkSettings.Networks}}{{$key}} {{end}}',
        container_name,
    ])
    if rc != 0:
        click.echo(f"   ! {container_name}: container not running or not found")
        return False

    expected_net = f"{plane_name}-net"
    # Docker Compose may prefix network names with the project directory name
    networks = stdout.strip().split()
    has_expected = any(expected_net in net for net in networks)
    if has_expected:
        click.echo(f"   ✓ {container_name}: on network containing '{expected_net}'")
        return True
    else:
        click.echo(f"   ! {container_name}: expected network '{expected_net}', found: {networks}")
        return False


def _check_no_ping(src_container: str, dst_container: str) -> bool:
    """Verify that src cannot ping dst (ping should fail)."""
    # Get dst IP
    rc, dst_ip, _ = _run_docker([
        "inspect", "--format",
        '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}',
        dst_container,
    ])
    if rc != 0 or not dst_ip:
        click.echo(f"   ! {src_container} -> {dst_container}: could not get IP for {dst_container}")
        return False

    # Attempt ping — we expect this to fail
    rc, stdout, stderr = _run_docker(
        ["exec", src_container, "ping", "-c", "1", "-W", "2", dst_ip],
        timeout=10,
    )
    if rc != 0:
        click.echo(f"   ✓ {src_container} cannot reach {dst_container} ({dst_ip}) — isolation confirmed")
        return True
    else:
        click.echo(f"   ! {src_container} CAN reach {dst_container} ({dst_ip}) — isolation BROKEN")
        return False


def _check_config_readonly(container_name: str) -> bool:
    """Verify config/ is mounted read-only by attempting to write."""
    rc, _, stderr = _run_docker(
        ["exec", container_name, "touch", "/app/config/test_isolation"],
        timeout=5,
    )
    if rc != 0:
        click.echo(f"   ✓ {container_name}: /app/config/ is read-only")
        return True
    else:
        # Clean up the test file
        _run_docker(["exec", container_name, "rm", "-f", "/app/config/test_isolation"])
        click.echo(f"   ! {container_name}: /app/config/ is WRITABLE — should be read-only")
        return False


def _check_memory_writable(container_name: str) -> bool:
    """Verify memory/ is writable by attempting to create and remove a file."""
    rc, _, stderr = _run_docker(
        ["exec", container_name, "touch", "/app/memory/test_isolation"],
        timeout=5,
    )
    if rc != 0:
        click.echo(f"   ! {container_name}: /app/memory/ is NOT writable — should be writable")
        return False

    # Clean up
    _run_docker(["exec", container_name, "rm", "-f", "/app/memory/test_isolation"])
    click.echo(f"   ✓ {container_name}: /app/memory/ is writable")
    return True
